## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
 allow_failures:
 - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
 apt: # apt-get for linux
   packages:
   - libgtk-3-dev
# before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
  - git clone https://github.com/JuliaRegistries/General  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "General"))')  
  - git clone https://github.com/SISL/Registry  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "SISL"))')  
  - git clone https://github.com/JuliaPOMDP/Registry  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "JuliaPOMDP"))')  
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes -e 'import Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                Pkg.add("Documenter"); 
                                Pkg.add(PackageSpec(url="https://github.com/sisl/Records.jl")); 
                                Pkg.add(PackageSpec(url="https://github.com/sisl/Vec.jl"));
                                Pkg.add(PackageSpec(url="https://github.com/sisl/AutomotiveDrivingModels.jl"));
                                Pkg.add(PackageSpec(url="https://github.com/sisl/AutoViz.jl"));
                                Pkg.add(PackageSpec(url="https://github.com/sisl/AutoUrban.jl"));
                                Pkg.add(PackageSpec(url="https://github.com/sisl/AutomotiveSensors.jl"));
                                Pkg.add("POMDPs");
                                using POMDPs;
                                POMDPs.add_registry();
                                Pkg.add(PackageSpec(url="https://github.com/sisl/AutomotivePOMDPs.jl"));
                                Pkg.develop(PackageSpec(path=pwd()));
                                Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
